// <auto-generated />
namespace Introduccion_EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class columna_nueva : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(columna_nueva));
        
        string IMigrationMetadata.Id
        {
            get { return "202104151515236_columna_nueva"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
